services:
  web:
    build: .
    container_name: fsuvius
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - web
    volumes:
      - type: bind
        source: ./data
        target: /fsuvius/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
networks:
  web:
    external: true
