services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: fsuvius_app
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - web
    volumes:
      - db:/home/fsuvius/db
    environment:
      - HOST=fsu.cosi.clarkson.edu
      - SECRET_KEY=[_____CHANGEME_____]
  
  proxy:
    build:
      context: .
      dockerfile: docker/proxy.Dockerfile
    container_name: fsuvius_proxy
    restart: unless-stopped
    expose:
      - 80
    networks:
      - web
    depends_on:
      - app

networks:
  web:
    external: true

volumes:
  db: {}
