services:
  web:
    build: .
    container_name: fsuvius
    restart: unless-stopped
    ports:
      - "9039:8080"
    volumes:
      - type: bind
        source: ./data
        target: /fsuvius/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
